apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dreamkast-api-mock
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
images:
- name: /dreamkast-api-mock
  newTag: cb641a6f5cb61cc5e8dc1aeed0308d67f82f1b5c
- name: 607167088920.dkr.ecr.ap-northeast-1.amazonaws.com/dreamkast-api-mock
  newTag: e067f9b7bb32b53723f148999043556c5fb2a14e
- name: dreamkast-api-mock
  newName: 607167088920.dkr.ecr.ap-northeast-1.amazonaws.com/dreamkast-api-mock
  newTag: 329df4c0aa0cb53796a112aae00dcf7530b5b26e
